Update build system

diff --git a/.github/workflows/updatedebianchangelog.yml b/.github/workflows/updatedebianchangelog.yml
--- a/.github/workflows/updatedebianchangelog.yml
+++ b/.github/workflows/updatedebianchangelog.yml
@@ -2,11 +2,11 @@
 
 on:
   push:
-    # Sequence of patterns matched against refs/tags
+    branches:    
+      # Push events on main branch
+      - main
     tags:
       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
-
-name: update debian changelog
 
 jobs:
   build:
@@ -18,48 +18,24 @@ jobs:
       with:
         ref: master
         fetch-depth: 0
-    - name: Run info        
+    - name: Run test build and update debian changelog 
       run: |
-            echo "github.workspace ${{ github.workspace }}"
-            buildnum=0
-            CURR_DIR=$(pwd)
-            revision="HEAD"
-            buildName="Auto-build"
-            FullCommit=$(git -C $CURR_DIR rev-parse $revision)
-            if [ -z ${FullCommit+x} ]; then
-                echo "Failed on get commit for $revision revision [$FullCommit]";
-                exit 1;
-            fi
-            echo "* FullCommit [$FullCommit]"
-            LastTag=$(git -C $CURR_DIR describe --tags --first-parent --match "*" $revision)
-            echo "* TAG [$LastTag]"
-            if [ -z ${LastTag+x} ]; then
-              LastTag="0.0.0.$buildnum"
-              echo "Failed on get tag for revision $revision - defaulting to $LastTag"
-            fi
-            parsestr="$(echo -e "${LastTag}" | sed -e 's/^[a-zA-Z]*//')"
-            Major=`echo "${parsestr}" | awk -F"[./-]" '{print $1}'`
-            Minor=`echo "${parsestr}" | awk -F"[./-]" '{print $2}'`
-            buildName=`echo "${parsestr}" | awk -F"[./-]" '{print $3}'`
-            echo -e "* [$LastTag] => [$Major.$Minor.$Patch.$buildnum]"
-            echo -e "* Release Name [$buildName]"
-            gitTagList=$(git -C $CURR_DIR tag --sort=-version:refname)
-            gitTagListCount=$(echo -n "$gitTagList" | grep -c '^')
-            if [[ 1 -ge "$gitTagListCount" ]]; then
-                echo "Use all entries for a release note:"
-                releaseNote=$(git -C $CURR_DIR log --date=short --pretty=format:"  * %ad [%aN] %s")
-            else
-                tmpval=$(echo "${gitTagList}" | awk 'NR==2{print}')
-                gitTagRange="${tmpval}..${revision}"
-                echo "Release note range [$gitTagRange]"
-                releaseNote=$(git -C $CURR_DIR log "$gitTagRange" --date=short --pretty=format:"  * %ad [%aN] %s")
-            fi
-            echo "***** Prepare distr changelog";
-            echo "logview (${Major}.${Minor}.${buildnum}) unstable; urgency=medium"         > "${CURR_DIR}/debian/changelog"
-            echo ""                                                                        >> "${CURR_DIR}/debian/changelog"
-            echo "$releaseNote"                                                            >> "${CURR_DIR}/debian/changelog"
-            echo ""                                                                        >> "${CURR_DIR}/debian/changelog"
-            echo " -- chipmunk.sm <dannico@linuxmail.org>  $(LANG=C date -R)"              >> "${CURR_DIR}/debian/changelog"
-            cat "${CURR_DIR}/debian/changelog"
-      
+          if [[ "$RUNNER_OS" == "Linux" ]]; then
+              chmod +x build.sh;
+              ./build.sh -b 0 -c GCC -x "linux" -n "Test";
+          elif  [[ "$RUNNER_OS" == "Windows" ]]
+              echo "$RUNNER_OS";
+          elif [[ "$RUNNER_OS" == "macOS" ]]
+               echo "$RUNNER_OS";
+          else
+               echo "Error $RUNNER_OS";
+               exit 1;
+          fi
+    - name: Commit debian changelog
+      run: git commit -m 'Autoupdate changelog' -- ./debian/changelog
+    - name: Push changes to master
+      uses: ad-m/github-push-action@master
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        force: true 
 
